# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-25 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60)),
                ('repo', models.CharField(max_length=100)),
                ('stars', models.IntegerField()),
                ('colabs', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
            ],
        ),
    ]
